def throw_exception():
    raise Exception("Something went wrong")
